version: "3"

services:
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Dublin
    volumes:
      - /media/config/nzbget:/config
      - /media/usenet:/data/usenet
    ports:
      - 8081:6789
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - VERSION=docker
      - TZ=Europe/Dublin
    volumes:
      - /media/config/plex:/config
      - /media/media:/data/media
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Dublin
    volumes:
      - /media/config/radarr:/config
      - /media:/data
    ports:
      - 8083:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Dublin
    volumes:
      - /media/config/sonarr:/config
      - /media:/data
    ports:
      - 8084:8989
    restart: unless-stopped
