version: "3"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.2
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - ${HOME}/homelab-hyrule/config/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.entryPoints=web
      - traefik.http.routers.api.rule=Host(`traefik.hyrule.lan`) && PathPrefix(`/api`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.dashboard.entryPoints=web
      - traefik.http.routers.dashboard.rule=Host(`traefik.hyrule.lan`) && PathPrefix(`/`)
      - traefik.http.routers.dashboard.middlewares=dashboard_redirect@internal
      - traefik.http.routers.dashboard.middlewares=dashboard_stripprefix@internal
      - traefik.http.routers.dashboard.service=dashboard@internal

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    env_file:
      - env/common.env
    networks:
      - proxy
    volumes:
      - /media/config/nzbget:/config
      - /media/usenet/completed:/downloads/completed
      - /media/usenet/intermediate:/downloads/intermediate
    labels:
      - traefik.enable=true
      - traefik.http.routers.nzbget-https.tls=true
      - traefik.http.routers.nzbget-https.entrypoints=web-secure
      - traefik.http.routers.nzbget-https.tls.certresolver=default
      - traefik.http.routers.nzbget-https.middlewares=auth@file
      - traefik.http.routers.nzbget-https.rule=Host(`nzbget.jackc.ie`)
      - traefik.http.routers.nzbget-http.entrypoints=web
      - traefik.http.routers.nzbget-http.rule=Host(`nzbget.hyrule.lan`)
      - traefik.http.services.nzbget.loadbalancer.server.port=6789
    restart: unless-stopped

  plex:
    image: plexinc/pms-docker
    container_name: plex
    networks:
      - proxy
    ports:
      - 32400:32400
    env_file:
      - env/common.env
      - env/plex.env
    volumes:
      - /media/config/plex:/config
      - /media/media:/data/media
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex-https.tls=true
      - traefik.http.routers.plex-https.entrypoints=web-secure
      - traefik.http.routers.plex-https.tls.certresolver=default
      - traefik.http.routers.plex-https.rule=Host(`plex.jackc.ie`)
      - traefik.http.routers.plex-http.entrypoints=web
      - traefik.http.routers.plex-http.rule=Host(`plex.hyrule.lan`)
      - traefik.http.services.plex.loadbalancer.server.port=32400
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    env_file:
      - env/common.env
    volumes:
      - /media/config/radarr:/config
      - /media:/data
      - /media/usenet/completed:/downloads/completed
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr-https.tls=true
      - traefik.http.routers.radarr-https.entrypoints=web-secure
      - traefik.http.routers.radarr-https.tls.certresolver=default
      - traefik.http.routers.radarr-https.middlewares=auth@file
      - traefik.http.routers.radarr-https.rule=Host(`radarr.jackc.ie`)
      - traefik.http.routers.radarr.entrypoints=web
      - traefik.http.routers.radarr.rule=Host(`radarr.hyrule.lan`)
      - traefik.http.services.radarr.loadbalancer.server.port=7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    env_file:
      - env/common.env
    volumes:
      - /media/config/sonarr:/config
      - /media:/data
      - /media/usenet/completed:/downloads/completed
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr-https.entrypoints=web-secure
      - traefik.http.routers.sonarr-https.tls=true
      - traefik.http.routers.sonarr-https.tls.certresolver=default
      - traefik.http.routers.sonarr-https.middlewares=auth@file
      - traefik.http.routers.sonarr-https.rule=Host(`sonarr.jackc.ie`)
      - traefik.http.routers.sonarr.entrypoints=web
      - traefik.http.routers.sonarr.rule=Host(`sonarr.hyrule.lan`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
    restart: unless-stopped

networks:
  proxy:
    external: true
