api:
  dashboard: true
entryPoints:
  http:
    address: :80
providers:
    docker:
        watch: true
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
        network: proxy
    providersThrottleDuration: 10s
