api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"
providers:
  file:
    watch: true
    filename: /etc/traefik/traefik-dynamic.yaml
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: homelab-hyrule_proxy
  providersThrottleDuration: 10s
certificatesResolvers:
  default:
    acme:
      storage: "/etc/traefik/acme.json"
      keyType: RSA2048
      tlsChallenge: {}
log:
  level: DEBUG
